### ISSUE TITLE
Nix support

### ISSUE THREAD

**Issue by Jappie3** [Ferdi265/wl-restart#1]
Hi, first of all: thanks for creating wl-restart! It looks like an amazing tool that I'd love to use on Nix. Would it by ok for you if I created a MR that packages wl-restart using a Nix flake? (this would mean adding the flake.nix & flake.lock files to the repo)

**Comment by Ferdi265** [comment]
Hi!

Cool to see that you like it!

I'd prefer it if `wl-restart` is packaged via `nixpkgs` similar to how `wl-mirror` and `pipectl` are packaged, since I don't like putting packaging-/distro-specific files into the repo.

Otherwise I have no issues with this project being packaged.

**Comment by Jappie3** [comment]
all right, thanks for the quick reply! maybe it's time for my first contribution to nixpkgs 😆

**Comment by Ferdi265** [comment]
it seems someone else got there before you, a PR in nixpkgs already exists: https://github.com/NixOS/nixpkgs/pull/328635

**Comment by Jappie3** [comment]
was quite busy yesterday & hadn't looked at it yet, thanks for letting me know - knowing me I would've missed it and only noticed it at the last moment xD
